version: '3.8'

services:
  web-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-panel
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=web-panel-docker-secret
      - DB_PATH=/app/data/database.sqlite
      - UPLOAD_PATH=/app/uploads
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - web-panel-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: web-panel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web-panel
    networks:
      - web-panel-network
    profiles:
      - with-nginx

networks:
  web-panel-network:
    driver: bridge

volumes:
  uploads:
  logs:
  data: